### ISSUE TITLE
改良「封鎖內容農場」？

### ISSUE THREAD

**Issue by jmlntw** [danny0838/content-farm-terminator#1]
和原先的「封鎖內容農場」功能有點重複，是否考慮把這些改良功能推回去？

**Comment by danny0838** [comment]
這問題有點複雜。

首先，原「封鎖內容農場」套件的 Chrome 版和 Firefox 版是二位作者分別寫成，而且目前看來兩位似乎都沒有同時維護 Chrome 版和 Firefox 版的意願。

其次，本套件雖說是功能上改良，但程式碼是整個重寫及優化，要看原作者是否願意接受。

再來，本套件在功能上改了很多，加了一些功能，也拿掉了一些功能，差異可能已經大到應該視為另一個套件了。

我會再找時間和兩位作者談談，看他們是否有人願意接受這套程式碼及繼續維護。不過如上所述，可能會存在一些困難。
