### ISSUE TITLE
地址栏图标

### ISSUE THREAD

**Issue by dupontjoy** [danny0838/content-farm-terminator#13]
最近版本, 地址栏出现了图标, 感觉完全没有必要哇
![1](https://user-images.githubusercontent.com/4965288/32422801-87c5048e-c2dd-11e7-807e-6ffbd2f73542.jpg)

**Comment by danny0838** [comment]
有工具列按鈕直接進入選項會比較方便設定。另外，手機版如果沒有這個按鈕會無法進入選項頁面。

如果不需要，你可以自訂工具列把它拿掉。

**Comment by dupontjoy** [comment]
好的, 明白了
