### ISSUE TITLE
想詢問一下新增自動隱藏的功能

### ISSUE THREAD

**Issue by vpro16513428** [danny0838/content-farm-terminator#14]
假設偵測到內容農場
能不能直接令連結的`css : display:none`
然後這個功能可以切換讓使用者自行選擇要不要用這樣
畢竟打從一開始就看不到的話
就不會有好奇心的問題了

**Comment by danny0838** [comment]
技術上是不難做到，但結果會像下圖一樣網頁缺得莫名奇妙。

![default](https://user-images.githubusercontent.com/531417/32564321-e3350f72-c4ee-11e7-9c2a-01530a9105d0.png)

況且標示的目的是提醒，使用者仍保有檢查的權利。隱藏連結會讓使用者不知道連結網址，也難以查看。

**Comment by vpro16513428** [comment]
感謝回復 瞭解了!
