### ISSUE TITLE
aol.com 不應該放到 content farm

### ISSUE THREAD

**Issue by gslin** [danny0838/content-farm-terminator#17]
放 aol.com 太廣了，像是官方的 AIM 公告就被擋了：

https://help.aol.com/articles/aim-discontinued

**Comment by danny0838** [comment]
不曉得你有沒有研究過 aol.com 是因為哪些內容被封鎖的？有建議改成怎麼樣的封鎖範圍嗎？

**Comment by gslin** [comment]
no idea... 我看了一下 git blame，當初這些清單是怎麼來的...？

https://github.com/danny0838/content-farm-terminator/commit/5c9f015424efeaf954987e77d26c3cc211af2ef2

**Comment by danny0838** [comment]
都忘了是我自己加的XD 國外的網站當時比較多是從收集內容農場的發文中稍加篩選弄出來的。AOL 似乎和 Demand Media 一樣是個長期以來被詬病為內容農場的網站，雖然近年似乎慢慢在轉型。

**Comment by fei0316** [comment]
Aol.com 應該是理解成Yahoo 或者 msn 首頁的新聞吧？而且 Aol 也有很多互聯網服務，全部被擋就不合理了。另外也不知道內容農場的定義爲何，因爲我個人的理解是偷文偷圖才算，但 Aol 那些只能算是標題黨吧。

**Comment by danny0838** [comment]
內容農場的定義可以參考[這裡](https://github.com/danny0838/content-farm-terminator/tree/gh-pages)，主要以盜文盜圖盜影片和堆砌垃圾內容為主，加上一些附帶原則。

目前暫時找不太到 aol.com 被列入內容農場的理由，先解除封鎖。
