### ISSUE TITLE
helium.com 怎麼會在內容農場清單？

### ISSUE THREAD

**Issue by bestpika** [danny0838/content-farm-terminator#18]
https://www.helium.com
這應該是一個 IoT 相關產品的網站才對，怎麼會進內容農場？

**Comment by danny0838** [comment]
這項是沿用自《封鎖內容農場》套件，初步看起來是從一些談論內容農場的國外文章找來的。我有時間再細查。

**Comment by bestpika** [comment]
我想說我在 Google 的 IoT core 的文裡看到這連結前面標了內容農場，怕 XD

**Comment by bestpika** [comment]
@danny0838 哈囉，請問你有時間可以看一下這個網站了嗎？

**Comment by danny0838** [comment]
最近暫時沒時間馬上查。如果您個人認為它不是農場，可以自行加入白名單。

**Comment by penguinfuko** [comment]
helium.com 原本應該是個寫作的網站，是像yahoo知識+這樣的東西，由於反應良好，似乎被獨立成一篇篇文章，假使作者提交文章的內容排名足夠高的話，會由網站經由paypal 支付稿酬。

內容由網站的其他成員評定，但似乎因為並無相應檢查註冊成員的機制，導致有大量刷分數的行為，致使低品質文章橫出。加上網站本身對作者著作權的不重視與囂張的態度，在2014年結束經營。後被Helium Systems 收購，而後被解散。

用 Helium.com 資料比較少，依照另一個類似網站的批評，似乎曾經有大量買網域的行為。 
推薦關鍵字是 Helium Publishing 

現在域名被買走了，變成這樣一個自稱的平台
「Helium is the world’s first decentralized machine network powered by a blockchain」
故應該要去除被標為內容農場的行列。

解散說明：
https://www.heliumnetwork.com/helium-publishing-shut-faqs/

相關討論文章：
https://www.bookbusinessmag.com/article/rr-donnelley-acquires-helium-worlds-largest-writing-community/all/

https://www.verblio.com/blog/helium-publishing-360-content-writing-service-sinking-sunset
https://www.webemployed.com/how-to-earn-online-as-a-writer-at-helium/

**Comment by danny0838** [comment]
感謝提供資訊，先從黑名單移除。
