### ISSUE TITLE
兩個ptt偽站

### ISSUE THREAD

**Issue by zhtw2013** [danny0838/content-farm-terminator#19]
sexptt.tk
orzptt.tk

都是168ptt的域名
介面跟官方PTT的網頁版一模一樣
但是會在最後的推文加上廣告，做假推文。

推 99bio: 真心推薦! 廣告 廣告 廣告

請求加入內建清單！(168ptt本站已經在清單裡面了)

話說網頁的舉報表單只能提交一次？

**Comment by danny0838** [comment]
已加入名單。

舉報表單不限填寫一次。送出後再從表單的連結進入表單頁面就可以再填再送。
