### ISSUE TITLE
BuzzFeed 是新闻聚合网站。

### ISSUE THREAD

**Issue by Crystal-RainSlide** [danny0838/content-farm-terminator#20]
www.buzzfeed.com
BuzzFeed 是正常的新闻聚合网站，而且他们有自己的独家新闻，不是故意为之的内容农场。对它的abuse主要是因为它是个靠研究病毒式传播发家极品新兴媒体。然后，病毒式传播于内容农场大有区别：既不靠假消息，也不会小题大做、标题党，靠的是发掘内容本身的价值。不能将它移除的话，至少应当移至 类内容农场 这个清单。
也确信它不会故意发假新闻。

https://www.helium.com/
https://help.aol.com/articles/aim-discontinued
也都 没有 解封……时间有几个月了，如无发现这些网站的内容农场

最后，既然
> 
國外的網站當時比較多是從收集內容農場的發文中稍加篩選弄出來的

我很想看看是哪个国外网站这么酸，挂了这么多大网站……估计是把大量正常转发其他网站新闻的行为当做内容农场了，这是一个同 “把 MajorGeeks 当做默许流氓软件的网站” 一样愚蠢的错误。可惜找不到文章链接……唉，他们不怪流氓软件开发者，却怪软件网站。

推荐给假新闻网站和假冒网站单独定制警告内容
http://www.spam404.com/ 主要收录假冒网站

**Comment by Crystal-RainSlide** [comment]
这上面有一个 小 但是会逐日变大 的点：现在所有想活下去的新闻网站都打算或正在让自己的内容更容易被转发，也就是原初形式的病毒式推广。如果对这种行为穷追不舍，未来可能就没新闻网站可看了。

**Comment by danny0838** [comment]
你可以參考我們[判定內容農場的標準](https://github.com/danny0838/content-farm-terminator/tree/gh-pages)，不是「假消息」「小题大做」「标题党」「病毒式传播」，而是「大量盜用原創內容」「欺騙搜尋引擎」「只有轉貼而缺乏主題性、原創性、篩選與編輯」等等。

從大多數可找到的中英文資料看來，Buzzfeed 過去的確有大量盜用原創內容的記錄，因此過去是內容農場當無疑議，現在似乎有在轉型也開始有一些獨家新聞，但比例如何、現今是否仍有大量盜文事實等等，仍有待進一步調查。
