### ISSUE TITLE
方便的block xuite裡的內容農場

### ISSUE THREAD

**Issue by lion6230i** [danny0838/content-farm-terminator#22]
在google上找資料，尤其是找某些產品的開箱文，台灣通常會有兩個網站來源。
pixnet和xuite
pixnet比較簡單，就整個block，
u5sylviaiefm.pixnet.net
但xuite就比較麻煩，要像你整理的黑名單的方式blcok
/^https?://(?:m[.])?blog[.]xuite[.]net/n8h6f80xr3(?=[/?#]|$)/
是否考慮在右鍵增加一個直接parser url後面的使用者ID，不然每次想block都要copy然後再貼上，有點麻煩…
也就是直接跳出/^https?://(?:m[.])?blog[.]xuite[.]net/n8h6f80xr3(?=[/?#]|$)/ 讓使用者去點選。

**Comment by danny0838** [comment]
這類套件一開始是設計為針對網域，對於封鎖網域下特定 URL 算是輔助及擴充的功能，不容易做到和前者一樣方便。

自動把網址轉為適當的 RegExp 規則是個不錯的主意，但目前至少有幾個困難：
1. 每個網站的規則不同，因此我們可能必須針對所有網站做個別設定
2. 即使是同一個網站，對於特定的網址，使用者想要的 RegExp 也未必相同。你可能想要像我們提供的預設名單一樣封鎖子 ID，但也無法排除使用者想要封鎖子 ID 下特定頁面，或其他規則的可能性。

如果要實做，大概得讓使用者能自訂個別網站的解析方式。這裡有個困難是自訂解析方式需要自己寫程式碼，即使使用者能自己寫， WebExtension 系統基於安全理由也不允許把使用者提供的程式碼字串當成 JavaScript 程式碼執行。

**Comment by lion6230i** [comment]
如果用另一種方式呢？
按右鍵後，會出現封鎖整個網域和客製化封鎖，
客製化今鎖就直接parser網域後的字串
/aaa/bbb/ccc/ddd
然後依照使用者選擇，如果是aaa就直接產生一串block此網域aaa的RegExp，
讓使用者可以copy直接貼到自訂黑名單裡使用。

**Comment by danny0838** [comment]
這麼做 parser 難寫的問題還是沒解決啊。

**Comment by lion6230i** [comment]
java script 有split function.

var str = "How are you doing today?";
var res = str.split(" ");

不是像這樣用str.split("/")，就可以parser出來嗎？
單就xuite網站而言啦…
可能是我想的比較簡單…XD

**Comment by danny0838** [comment]
呃……難點我在 2 樓都說過了。如果只是把當下瀏覽的網址轉成 RegExp，那很簡單，問題是以 Xuite 為例，假如你目前正在瀏覽 `http://blog.xuite.net/wtf/blog/573966416`，用程式無腦轉 RegExp 以後會變成 `/^http://blog[.]xuite[.]net/wtf/blog/573966416$/`，但事實上你可能會想要的是 /^https?://(?:m[.])?blog[.]xuite[.]net/wtf(?=[/?#]|$)/。

這其中的差異，每個網站都不同，同一個網站的不同頁面也有不同的轉換方式，因此寫死的程式碼肯定是行不通的。那就必須允許使用者自訂「當目前的網址是如何如何，就採用何種何種解析方式」，而這樣的解析器相當於發明一種新的程式語言，很難實做。

**Comment by danny0838** [comment]
3.4.0 做出這功能了，不過轉換規則要自己加，正規表示式要自己學一下（[這裡](https://github.com/danny0838/content-farm-terminator/tree/gh-pages)有提供一些常見平台的轉換規則，可以參考）。沒辦法，這玩意兒就是比較複雜@~@
