### ISSUE TITLE
瀏覽器剛啟動會執行頁面中的連結

### ISSUE THREAD

**Issue by FlandreDaisuki** [danny0838/content-farm-terminator#25]
似乎是本套件和 uBlock Origin 衝突，單獨開啟不會發生的樣子

## Reproduce:

1. 打開瀏覽器「恢復先前的瀏覽狀態」跟關閉「關閉瀏覽器後清除歷史紀錄」的選項
2. 擴充套件只安裝本套件及 uBlock Origin
3. 保留任意頁面([例如此頁](https://www.techbang.com/posts/58439-raspberry-pi-3-google-aiy-voice-kit))後關閉瀏覽器
4. 再度開啟瀏覽器時，會自動連結到原瀏覽頁面中的任一連結，按上一頁可跳回

## Environment:

|OS|Browser|Extensions|
|:-:|:-:|:-:|
|Linux Mint 18.3| Firefox 62.0b18 (64bit) | 本套件 v3.3.2; uBO v1.16.16|
|Windows10| Firefox 61.0.2 tete009 | 本套件 v3.3.2; uBO v1.16.16|
|Windows10| Chrome 68.0.3440.75 | 本套件 v3.3.1; uBO v1.16.16|

**Comment by danny0838** [comment]
感謝回報，但我在以下環境都無法重現問題：

|OS|Browser|Extensions|
|:-:|:-:|:-:|
|Windows7| Firefox 62.0b17 | 本套件 v3.3.2; uBO v1.16.16|
|Windows7| Chrome 68.0.3440.106 | 本套件 v3.3.1; uBO v1.16.16|

用 Firefox 測試時，其中一次重啟瀏覽器有發生頁面跳轉，但後來重啟都沒再發生，無法排除是該網頁本身的問題。

Chrome Web Store 已上傳了 v3.3.2，但不曉得為何還沒更新到 v3.3.2，目前已重新發佈，再等等看會不會更新。

**Comment by zhtw2013** [comment]
@danny0838 
不止T客邦，很多頁面都能重現，T客邦只是因爲他廣告多，方便我重現而已。
舉個例子，連PTT Chrome套件版也會發生。
我不認爲是網頁本身的問題，因爲我已經用好幾個不同的瀏覽器設定檔來重現過了。

Chrome 68、Firefox Tete009 61.02版、Cent Browser(Chromium67)
我測試了7~8個瀏覽器設定檔，全部都重現過了

單獨開啓不會發生，跟UBO同時開啓就很容易重現。

**Comment by danny0838** [comment]
能否提供你的 UBO 設定值？

**Comment by zhtw2013** [comment]
@danny0838 UBO、終結內容農場，都是全新安裝的預設值就能實現了。

之前在PTT Chrome套件版的頁面結束瀏覽器，
然後下次開機就幾乎每次都重現(印象中就是每次重現)，會跳到PTT Chrome的按讚頁面。

比較容易重現的情況，像是網頁有連結到FB按讚頁面時，並非特定網頁，
能夠重現這個情況的網頁太多了，我也不知道是不是有什麼特殊條件。

**Comment by danny0838** [comment]
我再測試了幾次 Firefox 61.0.2 和 62.0b20，全新設定檔，只裝這兩個套件，測試了以下幾個前面提過的頁面：
- https://www.techbang.com/posts/58439-raspberry-pi-3-google-aiy-voice-kit
- https://openhome.cc/Gossip/JavaGossip-V1/ObjectConstructor.htm
- https://www.ptt.cc/bbs/NSwitch/M.1534819435.A.B92.html

很遺憾的，還是無法重現問題，或許還有什麼未談到的要素尚未發現？

如果可以，不曉得能提供一段成功重現問題的影片？

**Comment by zhtw2013** [comment]
@danny0838 
[重現影片連結](https://youtu.be/xhHOXmbMJGU)
Cent Browser 版本 3.5.3.50 (正式版本) (64 位元) (portable) (Chromium 67.0.3396.99)
uBlock Origin 1.16.16
終結內容農場 3.3.1
未安裝其他套件。

![image](https://user-images.githubusercontent.com/9501406/44612636-848ae780-a83c-11e8-8099-a6ea6954bcaf.png)

**Comment by zhtw2013** [comment]
老大，原因找到了嗎？ 我停用套件好一段時間了...有點影響使用體驗啊！

**Comment by danny0838** [comment]
目前還無法重現。可否再協助確認：

1. 此問題經常發生，但並非每次都會發生？

2. 發生時，是否重導向的目標頁面都是 uBlock 封鎖的頁面？

**Comment by zhtw2013** [comment]
1.經常發生，在我用的瀏覽器User data可以說是每次都發生的。(上次說過了啊...)
2.並非每次都是UBO封鎖頁面 有的時候是跳到網頁中的某個頁面 例如FB、G+的按讚連結
(上次說過了啊......)
3.不會。(上次說過了啊...)

**Comment by danny0838** [comment]
主要是要確認是否非必定發生（如果是必定發生，而我沒遇到，就一定有還不清楚的影響因素；如果不是必定發生，就機會只是我剛好沒遇到）。

目前還是無法重現，不過先做一個測試版排除某個或許可能和 uBO 衝突的機制。

測試方法：刪除或停用原來的終結內容農場。下載以下檔案，把副檔名改成 .xpi，拖曳到 Firefox 安裝，回報問題是否仍存在：
[content_farm_terminator-3.3.2.1-an+fx.zip](https://github.com/danny0838/content-farm-terminator/files/2364049/content_farm_terminator-3.3.2.1-an%2Bfx.zip)

**Comment by zhtw2013** [comment]
@danny0838 Fx測試版 發現暫時沒遇到這個情況了，
能夠推送一版正式版到Chrome應用商店跟Fx套件中心嗎？

我想用Chrome再測試一次。

**Comment by danny0838** [comment]
也簽了一個 [Chrome 測試版](https://chrome.google.com/webstore/detail/content-farm-terminator/ecpjpoefcloakmdegcjgcljibbjfcaib?hl=zh-TW)，可試試。

這版本只是為確認問題所在而做的測試，由於會破壞某些功能的正常運作，暫時不會當正式版釋出。如果問題確實是在這裡，那還要想辦法解決所有可能的衍生問題，頗麻煩的。

**Comment by zhtw2013** [comment]
測試新版幾天，發現沒遇到這個問題了，可能問題點你已經找到了。

**Comment by gslin** [comment]
我還是會遇到，大概半年了，這次跑來發現有人回報過這個問題...

**Comment by danny0838** [comment]
@gslin 能否麻煩您也試試上述的 Firefox 或 Chrome 測試版是否無此問題？

**Comment by zhtw2013** [comment]
我用測試版三個月了，用測試版之後沒遇到這個問題過了..
我把它當正式版在用了..
@danny0838

**Comment by gslin** [comment]
用上面提到的測試版看起來沒問題 (重開十次看起來 ok)，有機會更新正式版嗎？

**Comment by danny0838** [comment]
改用另一個方法處理，或許能不破壞功能地解決問題，麻煩幫我測試此版本是否還有衝突的問題。

[Firefox 測試版](https://github.com/danny0838/content-farm-terminator/files/2705352/addon-3.3.2.2-an%2Bfx.zip) (刪除或停用原來的終結內容農場，下載此檔案，把副檔名改成 .xpi，拖曳到 Firefox 安裝)
[Chrome 測試版](https://chrome.google.com/webstore/detail/content-farm-terminator/ecpjpoefcloakmdegcjgcljibbjfcaib?hl=zh-TW)

**Comment by gslin** [comment]
thanks，我剛剛把 `suspendTabsUntilReady` 改成 `true` 後測了十次都沒問題...

**Comment by danny0838** [comment]
已查到目前程式碼有些問題會導致網頁亂跳轉（不過這問題理論上和 uBO 無關），總之，下一版會先解決此問題。

**Comment by danny0838** [comment]
3.3.3 已上架，這問題就先這樣吧……
