### ISSUE TITLE
痞客幫相關的垃圾關鍵字廣告業配（SEO）有辦法封鎖嗎？

### ISSUE THREAD

**Issue by ctes940008** [danny0838/content-farm-terminator#26]
作者大大你好，最近我在Google搜尋一些3C產品時常會跳出部落格形式的廣告業配網站

有辦法隱藏這些網站嗎？（類似Google的Personal Blocklist）

可以搜尋看看這個關鍵字

tcell 冠元- tt650 240gb SSD
---------------------------------------------------------------------
常見網頁標題跟內容

標題：【產品】XXXX【購物網站】-介紹
           【產品】XXX【購物網站】-送禮
「這次和姊妹們發現這個購物網裡面的商品優惠或折扣就滿多的 而且滿常辦活動送更多優惠,」

標題：【評價】XXX
「經過多方比較後，發現 XXXX 居然曾造成搶購熱潮， 價格也很實在，重點是買的安心，到貨的速度還滿快的」

標題：商品XXX開箱
「最近常去逛的店歇業了，之後就好少到那邊晃啦，可是朋友一直問我 XXXX 那裡買比較便宜！」

標題：大心推薦-XXX【購物網站】
「同事昨天介紹這個給我 XXX ，說他已經有買了,也很滿意,所以推薦給我之後我就上網查了 XXX 的資料發現網友跟鄉民都非常的推薦」

標題：特賣 XXX 搶先看
「最近因為我自己想買直殺成本 XXX，相信許多人對他都有很深刻的印象！上購物網看相關推薦、開箱文、價格,評價、報價、規格」

標題：特賣會 XXX
「電腦週邊新品特賣會XXX，性能卓越、CP值超高！因為每年這時候買電腦週邊產品最便宜~折扣數也好！」

標題：熱銷商品 XXX
「所以我跟寶貝馬上googe一下,找看看有沒有 XXX 推薦評比或價格比較」

標題：送禮推薦 XXX 便宜
「 最近媽媽生日快到了，偷偷打聽後知道媽媽最近想買XXX」

標題：省錢 XXX 買便宜
「最近工作閒暇之餘去百貨工司看到 XXX 覺得還挺有興趣的. 印象中在網路上 XXX 的評價一直都挺高的」

**Comment by danny0838** [comment]
標示連結的效果就很好了，且標示相較於隱藏更容易實做，也比較中性，因此目前不考慮做隱藏的功能。
