### ISSUE TITLE
错误标识了维基页面

### ISSUE THREAD

**Issue by wsxy162** [danny0838/content-farm-terminator#27]
在Android的Firefox上安装了这个扩展，使用Google搜索出现标识了维基百科的情况，但是点进去又不会弹出警告页面，也就是实际没有拦截。
示例页面：
![unnamed](https://user-images.githubusercontent.com/6559703/48982508-70e26c00-f11e-11e8-8b1b-f38c57df5cb1.png)

地址：[Google（手机访问）](https://www.google.com/search?newwindow=1&client=firefox-b&q=%E9%9D%A2%E5%8C%85%E8%99%AB&oq=%E9%9D%A2%E5%8C%85%E8%99%AB&aqs=heirloom-srp&authuser=0)

**Comment by danny0838** [comment]
被標示的連結不是下面的維基百科頁面，而是「黃粉蟲」右邊圖片的連結，該連結的確是指向一個內容農場網站（盜用維基百科內容且未按CC-BY-SA 3.0 協議發布）。

Google 搜尋結果這樣布置讓人容易誤以為該圖片出自維基百科，是 Google 設計的問題，可以考慮向 Google 反映。

**Comment by wsxy162** [comment]
已反馈给 Google。电脑端页面显示多张图片可以看出是来自 Google 图片搜索的，但是手机端页面只显示一张，就会让人误解了。

**Comment by danny0838** [comment]
感謝您的回饋，由於已確認此問題並非本套件的問題，關閉議題。
