### ISSUE TITLE
能不能把封锁内容增加开关功能？

### ISSUE THREAD

**Issue by ghost** [danny0838/content-farm-terminator#28]
浏览一些自定义网址，但是提示是内容农场后，继续进去就是被处理过的页面。建议在设置面板增加虽然是内容农场，但是也可以进去，就是这个功能可以开关。
另外，能不能增加网络白名单功能，用绿色图标标识，这样就把自己常进入的网址作一个标识，这样方便错误进入一些不合适的网址。

**Comment by danny0838** [comment]
1.目前不考慮，想看原網站內容可以把它加進白名單，這樣比較麻煩，不過這是刻意設計的，因為設黑名單的網站就是不鼓勵看，處理過的頁面會把廣告刪除，這樣就算看了也不會給農場主賺到廣告流量；如果允許直接進去很多人就會直接進去，農場主繼續爽賺，達不到抵制效果。

2.網頁白名單要再考慮，畢竟一般而言白名單不會太長，而且本來就可以雲端同步了。

**Comment by danny0838** [comment]
3.6.* 加上了暫時解鎖的功能，不過有計時限制，避免常態性解鎖。

**Comment by danny0838** [comment]
網頁白名單目前不打算考慮。關閉議題。
