### ISSUE TITLE
我可以修改您的插件吗

### ISSUE THREAD

**Issue by nuosi** [danny0838/content-farm-terminator#29]
尊敬的作者您好，很高兴您开发了这个插件。
我很喜欢这个插件，我想要插件弹出的网页是弹出一个界面提示功能。因为我在浏览facebook的时候，不喜欢一些专页或社群，但是终结农场插件会弹出一个很大的界面来拦阻，我继续浏览就是插件处理过的页面。很希望能有个开关，只保留检测网页，标注黑名单里的网页功能。

不知道我是否能修改您的插件，仅限于自己使用。不会发布到网络。我其实不懂这些语言，只是喜欢。

**Comment by danny0838** [comment]
1. 請整理一下標題和內文，若24小時未處理，我會自己改。

2. 意思是把標示功能和封鎖功能分開並且可個別設定是否使用？技術上可以做到，不過對本專案核心實務上作用似不大，加上改起來有些複雜，目前暫無打算這樣做。

3. 只要符合 GPL-3.0 你想怎麼改怎麼用都可以。
