### ISSUE TITLE
请问能不能增加封锁社交网站的部分链接功能？

### ISSUE THREAD

**Issue by nuosishizi** [danny0838/content-farm-terminator#31]
您好，目前内容终结农场能封锁一些facebook、推特等链接，但是我要自己封锁的话，就不是很方便，请问能不能增加一键封锁当前社交网站的固定个人、专页链接。谢谢

**Comment by danny0838** [comment]
設定好網址轉換規則，就可以直接用右鍵封鎖。如果不太會設，可以參考[後台資料庫](https://github.com/danny0838/content-farm-terminator/tree/gh-pages) 現有的轉換規則。
