### ISSUE TITLE
请问这些表达式能放到Google试算表或excel里用吗？

### ISSUE THREAD

**Issue by nuosishizi** [danny0838/content-farm-terminator#32]
我想在试算表里批量转换我要加入黑名单的网址。请问这些表达式能放到Google试算表或excel里用吗？如何使用呢？  我用函数 REGEXEXTRACT，不能直接使用。
另外，能不能增加识别网址服务器在中国，则自动屏蔽的功能，例如插件获取who.ip的数据来识别页面网址，则根据中国ip段提示。

/^https?://(?:(?:[\w-]+\.)?facebook\.com(?:/|\b[^#]+#!/)|(?:fb|m)\.(?:com|me)/)groups/(\d+)(?=[/?#]|$)/ /^https?://(?:(?:[\w-]+\.)?facebook\.com(?:/|\b[^#]+#!/)|(?:fb|m)\.(?:com|me)/)groups/$1(?=[/?#]|$)/
/^https?://(?:(?:[\w-]+\.)?facebook\.com(?:/(?:pg/)?|\b[^#]+#!/)|(?:fb|m)\.(?:com|me)/)(?:[^?#]+/)?(?:[^/?#]+-)?(\d+)(?=[/?#]|$)/ /^https?://(?:(?:[\w-]+\.)?facebook\.com(?:/(?:pg/)?|\b[^#]+#!/)|(?:fb|m)\.(?:com|me)/)(?:[^?#]+/)?(?:[^/?#]+-)?$1(?=[/?#]|$)/
/^https?://(?:(?:[\w-]+\.)?facebook\.com(?:/(?:pg/)?|\b[^#]+#!/)|(?:fb|m)\.(?:com|me)/)(?!\w+\.php(?:\?|$))([\w.-]+)(?=[/?#]|$)/ /^https?://(?:(?:[\w-]+\.)?facebook\.com(?:/(?:pg/)?|\b[^#]+#!/)|(?:fb|m)\.(?:com|me)/)$1(?=[/?#]|$)/
/^https?://(?:\w+\.)?twitter\.com/([\w-]+)(?=[/?#]|$)/ /^https?://(?:\w+\.)?twitter\.com/$1(?=[/?#]|$)/

**Comment by danny0838** [comment]
轉換規則的運作比較複雜，Google表單和Excel的公式無法處理，需要用巨集或寫個小程式。我們會研究能否讓黑/白名單填入網址時也自動套用轉換規則，這樣就不必專門寫個東西來做批次轉換，不過目前還有一些問題要克服。

另一個問題又更複雜了，麻煩另發Issue討論，感謝。

**Comment by danny0838** [comment]
3.8.5 已增加此功能，現在直接在黑名單或白名單填入網址，就會自動用轉換規則轉換了。
