### ISSUE TITLE
同名稱不同域名有高度為同農場之可能性，可以建立對應機制

### ISSUE THREAD

**Issue by leo424y** [danny0838/content-farm-terminator#35]
![image](https://user-images.githubusercontent.com/1384394/71434614-464b5400-2720-11ea-8a53-f7e71f7a4dfe.png)
如圖， kanwatch.fun 與 kanwatch.me 應為同農場，或許可一併擋下

**Comment by danny0838** [comment]
感謝回報。

我們是有一些機制去自動探索可能和黑名單中內容農場相關的農場，但一樣從寫程式、管理、維護都有成本，沒辦法全天候不斷地做，也無法保證不會遺漏。
