### ISSUE TITLE
请问能否为内容农场列表制作一份abp规则格式的副本

### ISSUE THREAD

**Issue by rhjdvsgsgks** [danny0838/content-farm-terminator#38]
请问能否为内容农场列表制作一份abp规则格式的副本，这样可以用在某些无法安装此插件的浏览器上

**Comment by danny0838** [comment]
ABP也是有很多方言的，不見得都能通用。

能更清楚說明是哪個平台嗎？ABP具體是哪個程式？

**Comment by rhjdvsgsgks** [comment]
我是在手机上使用Firefox preview nightly+ublock，在另一台设备上我使用的是kiwi+ublock。kiwi本来是支持安装chrome插件的，但安装此插件后所有网页均无法打开，可能是插件和kiwi的兼容不是很好，又不想麻烦开发者单独适配kiwi，所以就想到了abp规则这种比较通用的方法

**Comment by danny0838** [comment]
> 我是在手机上使用Firefox preview nightly+ublock，在另一台设备上我使用的是kiwi+ublock。kiwi本来是支持安装chrome插件的，但安装此插件后所有网页均无法打开，可能是插件和kiwi的兼容不是很好，又不想麻烦开发者单独适配kiwi，所以就想到了abp规则这种比较通用的方法

如果手機Firefox能安裝ublock，應該也能安裝終結內容農場。kiwi沒試過但我想也是一樣的情況。

至於有沒有辦法弄出和uBlock相容的封鎖清單，要再研究。不過最近沒什麼時間:( 本套件的資料都是用 GPL 授權，可以的話自己做或找有興趣的高手做或許會更快。

**Comment by danny0838** [comment]
先試做了一個初版。但雖說是ABP 格式，其實只用 uBO 測試過，ABP 本身只擋來自黑名單網站的廣告和腳本卻不會阻擋網站本身。

不曉得jjc際上還有哪些工具支援 ABP 格式又能阻擋網站本身的？

https://github.com/danny0838/content-farm-terminator/tree/test-abp-dist/files/dist/blocklist

**Comment by rhjdvsgsgks** [comment]
[koolproxyR](https://github.com/user1121114685/koolproxyR) 也可以

**Comment by DanSnow** [comment]
https://github.com/danny0838/content-farm-terminator/blob/test-abp-dist/files/dist/blocklist/abp-content-farms.txt#L3075
這個應該寫成底下這樣可能會比較好
```plain
www.ettoday.net/dalemon$document
```

**Comment by danny0838** [comment]
> https://github.com/danny0838/content-farm-terminator/blob/test-abp-dist/files/dist/blocklist/abp-content-farms.txt#L3075
> 這個應該寫成底下這樣可能會比較好
> 
> ```
> www.ettoday.net/dalemon$document
> ```

我再考慮一下，實在不想針對單一規則做 ad hoc 處理……

**Comment by danny0838** [comment]
> [koolproxyR](https://github.com/user1121114685/koolproxyR) 也可以

看起來像是運行在 Linux 桌面版的東西，不過 Linux 桌面版使用者本來就能安裝能使用本工具的瀏覽器，並沒有非它不可。

目前手上只有 uBO 是比較容易取得、且我實際有在使用的工具，因此目前預計先推出 uBO 規則。至於 ABP 規則，我目前實在沒多的心力去研究，想加快進程就請協助測試並回報是否可用，或找其他有意願協助開發及測試的人，否則 ABP 規則將無限期擱置。

**Comment by rhjdvsgsgks** [comment]
正在用(ubo+kiwi/Firefox preview nightly)，有效果，暂时没有遇到问题，还有什么需要测试的吗？

**Comment by danny0838** [comment]
主要是確認規則能正確運作，能擋到該擋的，且不會擋到不該擋的。

再來，之前有人提到效能問題，因為 uBO 可能對所有 web request 跑規則，相較於本工具有可能發生效能問題，尤其是大量使用 RegExp 的社群農場清單 (sns-content-farms.txt)，所以也要試試會不會顯著影響效能。當然，能把清單優化更好。

不要用「幾乎」這個過度籠統的詞，對於我們輸出的規則，就只有能和不能正確運作而已，要弄清楚。

看來實質上除了 uBO 目前並沒有足夠明確的 ABP 規則集（能擋網站本身的）和測試工具。因此應該會先更名為 uBO 規則集。

**Comment by danny0838** [comment]
目前實測官方 AdBlockPlus 似乎無法使用相關規則阻擋內容農場網站載入（只能阻檔其中的圖片、腳本等），因此以 uBO 規則為主。參見 #51。
