### ISSUE TITLE
建议把标志做的醒目一点，最好是整个搜索结果都是红的。

### ISSUE THREAD

**Issue by forest2code** [danny0838/content-farm-terminator#40]

**Comment by danny0838** [comment]
這個需要研究。基本上把整個搜尋結果變色不太可能，因為每個網站的設計都不同，沒有固定的規則。至於標示更醒目比較可行一點，不曉得有沒有更具體的建議？

**Comment by gslin** [comment]
提個建議看看，是不是有機會針對搜尋引擎與知名的 social network 的結果先處理？(e.g. google, duckduckgo, yahoo, bing, ... for search engines, and facebook, twitter, plurk, ... for social networks)

這些管道算是一般人很容易接觸到的，如果可以先處理的話好像對於 ux 是個不錯的方案？

**Comment by danny0838** [comment]
@gslin 技術上可以做到，但除非有非常好的優化方案或特殊的必要性，否則原則上不針對特定站台做客製化樣式調整。原因是站台太多，一一客製化難以維護，且原站台改版反而可能出錯。

**Comment by usercao** [comment]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/13760476/165670753-f2b38a7d-1341-4430-a38a-bc7e55b42eb9.png">
我理解他的意思可能是想整个标题变红，这样会明显一点？

**Comment by danny0838** [comment]
終結內容農場將不會做對針對特定檢索引擎的進階處理。如有這方面的需求可安裝 uBlacklist 並訂閱[終結內容農場提供的 uBlacklist 版黑名單](https://danny0838.github.io/content-farm-terminator/zh/subscriptions-ublacklist)。
