### ISSUE TITLE
舉報 pixnet 上的內容農場

### ISSUE THREAD

**Issue by jloqfjgk** [danny0838/content-farm-terminator#43]
pixnet 上實在有太多內容農場，尚未列入黑名單的例子如下：
userid (.pixnet.net) | 理由
------------ | -------------
prisci61 | [1]
mcdonald11 | [1]
elizabeth75 | [1]
uwi1014508 | [1]
consta28 | [1]
r75fp79l | [1] [2]
t59xq59v | [1] [2]
g11oz48c | [1] [2]
j99jl13t | [1] [2]
r72ov24q | [1] [2]
z31lj15b | [1] [2]
f57bf55j | [1] [2]

##### 理由列表
1. 無篩選編輯的大量轉載（大量轉載 Yahoo奇摩知識+ 的內容）
2. 顯示相同且佔據極大篇幅的廣告 (`https://pic.pimg.tw/toye4441/1468746283-333116064.png`)

只要在 DuckDuckGo 以 `"系" "大學" "排名" site:pixnet.net` 搜尋，即可找到一堆漏網之魚。
以隨機字串作為 userid 的 pixnet 網域，十之八九都是內容農場。

**Comment by danny0838** [comment]
已處理。有些傢伙就是製造垃圾永不嫌多 =.=+
