### ISSUE TITLE
在Kiwi瀏覽器上運行會造成沒有回應

### ISSUE THREAD

**Issue by jdck** [danny0838/content-farm-terminator#44]
我在Android手機端的[Kiwi Browser](https://github.com/kiwibrowser)裡安裝了這個擴充功能，但無論開啟任何網站，都會讓整個分頁當掉 (停用此套件後就立刻恢復正常)

**Comment by danny0838** [comment]
測試了一下 Chromium-based 的 Kiwi 和 Yandex Browser 都有同樣問題，但桌機版的 Google Chrome 沒有。

手機版的 Kiwi 和 Yandex Browser 沒有很好的除錯工具，可能要調查一段時間才能知道了QQ

**Comment by jdck** [comment]
首先相當感謝作者大大的熱心測試🙇，抱歉還勞煩您到處詢問。

但很遺憾目前已經暫時不需要了。因為我初衷是想裝給長輩使用，但長輩疑心病比較重，認定我在他手機上亂搞，並已禁止我再接觸他的手機😓

**Comment by danny0838** [comment]
感謝回覆，不過在 Kiwi Browser 的問題的確還存在，之後再努力研究解決方案

幫長輩安裝前，還是建議先做好溝通哦。

**Comment by danny0838** [comment]
Suspected to be a same case of #47

**Comment by Bob-YsPan** [comment]
我也安裝了Kiwi並且安裝了你的擴充套件
交叉測試測試了一些狀況
希望可以給你們除錯做參考：

Kiwi(arm64-v8a)版本
裝置：ZenFone 4 ZE554KL S630 Android 9
刪除網頁提供的大清單可以正常工作
(自己匯入大概200-300筆內容農場清單使用中)
只要匯入網頁提供的完整清單，就會導致當機
(網頁、擴充功能設定頁面沒有回應)

Kiwi(X86)版本
裝置：ZenFone 2 ZE551ML Atom Z3580 Android 6.0.1
完全正常(網頁的大清單能正常載入)

目前我想到的臨時解法是做一個比較小的清單，並且依據發現到的內容農場慢慢增加清單，把清單放在自訂黑名單的位置，然後暫時不匯入網路的大清單
(裝好擴充功能的時候趕快操作，把網路匯入的網址刪除並儲存)

希望對想用擴充功能又讓網頁瀏覽器卡住的有點幫助

**Comment by Bob-YsPan** [comment]
補充：
附上截圖
ZenFone 4
![Screenshot_20210312-165405853](https://user-images.githubusercontent.com/46966555/110916396-5ed06b80-82de-11eb-8945-44917537b44c.png)
![Screenshot_20210312-165341005](https://user-images.githubusercontent.com/46966555/110916405-6132c580-82de-11eb-8b3b-4aa1ebfcda66.png)

**Comment by danny0838** [comment]
4.0.* 版嘗試改良規則比對演算法，標準封鎖規則不再是線性速度（10000條規則不會花10000倍的比對時間）。此外也調整了黑名單，簡化重複的正規表示式。

我自己用手機測試 Kiwi Browser Git210216 版 + 終結內容農場 Beta 4.0.0.4，使用最新的標準內容農場清單+社群內容農場清單（可刪除兩個名單=>儲存=>重新加入兩個名單=>儲存，以強制更新黑名單），已無明顯的卡頓問題。但改用 3.* 版終結內容農場或用舊版的黑名單都還會有卡頓，看起來主要應該就是效能問題。

測試檔案如下，大家也可以試試。

終結內容農場 Beta 4.0.0.4 for Chromium (下載後解出 .crx 檔，用開發人員模式安裝）
[ecpjpoefcloakmdegcjgcljibbjfcaib_main.zip](https://github.com/danny0838/content-farm-terminator/files/6532111/ecpjpoefcloakmdegcjgcljibbjfcaib_main.zip)

終結內容農場 Beta 4.0.0a4 for Firefox
[addon-4.0.0a4-an+fx.zip](https://github.com/danny0838/content-farm-terminator/files/6532112/addon-4.0.0a4-an%2Bfx.zip)

**Comment by danny0838** [comment]
目前看來主因是效能問題，4.* 版已正式上架，應該已解決。如果還有遇到類似狀況請再回報。

**Comment by Bob-YsPan** [comment]
> 補充：
> 附上截圖
> ZenFone 4

已經明顯改善囉
回報一下
