### ISSUE TITLE
舉報疑似內容農場

### ISSUE THREAD

**Issue by jloqfjgk** [danny0838/content-farm-terminator#46]
本人檢視[舉報記錄](https://goo.gl/15jJAJ)後，發現當中有部分記錄可能因為回報者未有提供足夠資訊而被忽略，未被列入黑名單。

* `exceptionshub.com`
  * 例子：`https://exceptionshub.com/javascript-best-practices-of-timeout-after-ajax-call.html`，似乎抄襲 stackoverflow 的[這條問題](https://stackoverflow.com/questions/60317039/best-practices-of-timeout-after-ajax-call)，但該網頁未有指出原文來自 stackoverflow 。
* `pinkupost.com`
  * 例子：`http://pinkupost.com/%E6%A3%AE%E4%B8%83%E8%8F%9C-x-%E4%B8%AD%E6%9D%91%E5%80%AB%E4%B9%9F%E7%B5%84cp%EF%BC%81%E5%85%B1%E6%BC%94%E3%80%8C%E9%80%99%E4%BB%BD%E6%84%9B%E8%A6%81%E5%8A%A0%E7%86%B1%E5%97%8E%EF%BC%9F%E3%80%8D/`，疑似未經授權翻譯[モデルプレス的文章](https://mdpr.jp/news/detail/2211024)。
    * 從 https://mdpr.jp/attention 可見，モデルプレス的文章禁止擅自引用、複製、轉載。若 `pinkupost.com` 果真有獲得授權，應會註明「本文章獲 XXX 公司 / XXX 網站 授權轉載」，而非只說明資料來源為モデルプレス。
      * 該網站的其他文章也似乎是未經授權的翻譯，並說明 "Photos credit to all respective photographer and owner" 。
        例子：`http://pinkupost.com/%e7%b9%bc%e3%80%8e%e7%8a%ac%e9%b3%b4%e6%9d%91%e3%80%8f%e4%b9%8b%e5%be%8c%ef%bc%8c%e3%80%8c%e6%81%90%e6%80%96%e4%b9%8b%e6%9d%91%e3%80%8d%e7%b3%bb%e5%88%97%e7%ac%ac2%e5%bd%88%e7%a2%ba%e5%ae%9a%e8%a3%bd/`
        若獲授權轉載，理應準確、清楚說明相關圖片、文字的著作權擁有者才是。

**Comment by danny0838** [comment]
已處理，感謝提供資訊。

我們外文功力不高，可能要大家一起協助調查XD
