### ISSUE TITLE
YouTube clone

### ISSUE THREAD

**Issue by jloqfjgk** [danny0838/content-farm-terminator#48]
`https://kzclip.com`
以上網站疑似為 YouTube clone ，例如：
原影片：`https://www.youtube.com/watch?v=QJgRN_ZP9yk`
該網站：`https://kzclip.com/video/QJgRN_ZP9yk/die-neusten-und-coolsten-s%C3%BC%C3%9Figkeiten-frittieren-mit-joey-s-jungle-%F0%9F%98%8D%F0%9F%8D%AD.html`

這類網站應該符合條件「無篩選編輯的大量轉載」。

-----

註：運行 [Invidious](https://github.com/iv-org/invidious) 的網站不算是 YouTube clone ，因為 Invidious 沒有廣告或 trackers ，開放源碼，是 YouTube 的替代 front-end 。

**Comment by danny0838** [comment]
應該算是，影片和留言都原封不動 copy 過去，但是有些最新影片沒有，因此也不算 Proxy （就算是 Proxy 也應該要有來源聲明或適當的 credit，但這個站是整個換成自己的 mark）

已加入黑名單
