### ISSUE TITLE
YouTube clone

### ISSUE THREAD

**Issue by jloqfjgk** [danny0838/content-farm-terminator#49]
我發現更多 YouTube copiers 的網域：
* `ruclip.com`
  * 詳情可參考[此 Reddit 文章](https://old.reddit.com/r/youtube/comments/73meyq/ruclipcom_is_a_website_which_looks_like/)
* `ru-clip.net`
  * `https://skubny.ru-clip.net/xizvCi0UAzM/edifier-s1000mkii-vs-edifier-r1700bts-sound-frequency-response-comparison.html`
  * `https://www.youtube.com/watch?v=xizvCi0UAzM`

**Comment by danny0838** [comment]
感謝回報，已加黑名單
