### ISSUE TITLE
能提供去除右鍵選單的方式嗎?

### ISSUE THREAD

**Issue by dtxx** [danny0838/content-farm-terminator#5]
"blockTab": {
	    "message": "將此分頁的網域加入黑名單",
	    "description": "Context menu blocker on tab"
	  },
	
	  "blockPage": {
	    "message": "將此頁面的網域加入黑名單",
	    "description": "Context menu blocker on page"
	  },
	
	  "blockLink": {
	    "message": "將此連結的網域加入黑名單",
	    "description": "Context menu blocker on link"
	  },
	
	  "blockSelection": {
	    "message": "將選取文字網域加入黑名單",
	    "description": "Context menu blocker on selection"
	  },
	
	  "blockDomain": {
	    "message": "將此網域加入黑名單：",
	    "description": "Prompt for blocking domain"
	  },

這幾個功能 我常常誤觸OTZ
會提供去除這些選項的方式嗎?

**Comment by FlandreDaisuki** [comment]
我寫了一個版本丟 PR #6 了
就看作者接不接受了 😃

**Comment by FlandreDaisuki** [comment]
目前我都會在我的 [release](https://github.com/FlandreDaisuki/content-farm-terminator/releases) 放上 rebase 到最新版的 build
單純作為 **進階選項** (目前也就只有右鍵選單的選項)測試用途
有需要的人也歡迎幫忙試試看有沒有 bug

**Comment by danny0838** [comment]
為了避免大家等太久，新版 (2.4.0) 先把切換右键選單指令的選項加上去了。

進階選項的設計就先備查，等以後擴充新選項時再來煩惱吧XDD
