### ISSUE TITLE
在M1 Mac上会导致 Chrome冷启动一段时间内无法打开网页

### ISSUE THREAD

**Issue by Actuallymax** [danny0838/content-farm-terminator#50]
在M1 Mac上会导致 Chrome冷启动一段时间内无法打开网页，等几分钟就好了。

卸载这个插件一切正常

**Comment by danny0838** [comment]
懷疑和 #47 是同樣問題

**Comment by danny0838** [comment]
因無進一步回應，關閉議題。照理說處理了 #47 後應該會改善。如果仍有問題請重新測試和回報。
