### ISSUE TITLE
建議提供hostfile以及uBlock Origin相容設定檔

### ISSUE THREAD

**Issue by ghost** [danny0838/content-farm-terminator#51]
由於Android版Firefox暫不支援終結內容農場，也許可暫時作為替代方案，感謝。

**Comment by danny0838** [comment]
hostfile 我不熟，不曉得是否有規則文件？

#38 有試做 ABP (其實是 uBO) 規則轉換腳本，有興趣可以研究一下。

**Comment by hashashin1191** [comment]
> hostfile 我不熟，不曉得是否有規則文件？
> 
> #38 有試做 ABP (其實是 uBO) 規則轉換腳本，有興趣可以研究一下。

指套用於/etc/hosts的檔案，從DNS層面阻擋內容農場。
可以相容於各作業系統，也能套用在uBlock Origin和Android的AdAway，只是不會出現精美的警告畫面，實作的話需要架設一個HTTP Server再根據域名顯示警告頁面。
```
# /etc/hosts
127.0.0.1   kknews.cc
127.0.0.1   read01.com
127.0.0.1   codertw.com
127.0.0.1   buzzhand.com
127.0.0.1   buzzorange.com
127.0.0.1   teepr.com
127.0.0.1   ptt01.cc
```

**Comment by danny0838** [comment]
hosts 似乎不支援子網域篩選和 RegExp，這樣很難處理，或者轉換後遺失一大堆規則……

**Comment by hashashin1191** [comment]
hosts能處理的的確有限。原本黑名單的規則中有*星號，除了blogspot.*以外不知道該替代成什麼?
```sh
SED1="s/\/\//#/g"
SED2="s/blogspot.\*/blogspot.com/g"
SED3="s/^/127.0.0.1\t/"
wget -nc "https://danny0838.github.io/content-farm-terminator/files/blocklist/content-farms.txt"
(cat content-farms.txt | grep -v https) > content-farms-host.txt
sed -i "${SED1};${SED2};${SED3}" content-farms-host.txt
```

**Comment by DanSnow** [comment]
@hashashin1191 uBO 的 filter 不是已經有了嗎？
@danny0838 我覺得提供 hosts 檔雖然要放棄掉 RegExp 等規則，但對於沒辦法支援 uBO filter 的環境，我覺得這是必要的一個取捨，只是該不該由這個 repo 來提供我覺得可以再考慮，內容農場越來越多的情況下，維護 list 可能會比維護程式本身要來的複雜

**Comment by danny0838** [comment]
@hashashin1191 @DanSnow Blogger 支援 blogspot.tw 等頂層網域，只用 blogspot.com 無法完整封鎖。如果要自動轉換，光從 `blogspot.*` 無法反推該轉換成哪個頂層網域，如果要每個都轉成 blogspot.com + blogspot.tw + blogspot.us + ... 則可能讓清單爆炸性成長...

而 RegExp 規則該怎麼自動轉換也不好決定.....

就像有人負責定期把 Git 的程式碼移植到 Git for Windows，兩位如果有心，可以自己維護一個 repo 供 hostfile 或 uBO 使用，只要說清楚原始檔來自這個 repo 並且把轉換腳本公開即可。

**Comment by c2xusnpq6** [comment]
https://github.com/FutaGuard/FutaFilter/raw/master/nofarm_hosts.txt
https://github.com/festum/anti-bias-media/raw/master/ublacklist.txt
@danny0838 adblock規則相容性?

**Comment by DanSnow** [comment]
雖然說是有點久的 issue 了，不過我這邊把我以前寫的自己用的轉換成 uBO 規則的程式開源出來了，也弄了個會每天自動更新的 Github Action ，目前會無視 regex 的規則，只轉換 host 的部份 https://github.com/DanSnow/convert-content-farm-list

**Comment by danny0838** [comment]
@DanSnow 謝謝。能加個操作說明會更好。因為這樣看我也不清楚如何使用XD

**Comment by DanSnow** [comment]
加了個簡單的操作說明了

**Comment by danny0838** [comment]
我指的是 CLI script 如何執行。XD 不過有提供如何使用轉好的 uBO 規則總是好一點。

另外不提供 regex 規則的原因是？終結內容農場和 uBO 的 regex 規則應該差不多吧？

**Comment by DanSnow** [comment]
主要是因為 uBO 的主要規則並不是 regex ，而是有另外一種 syntax ，雖然 regex 的規則也是支援的，但可能會有效能問題，加上 uBO 是對所有的 request 執行規則的，目前是在打算要不要針對現有的 regex 各別寫專門的轉換規則，把 regex 轉成 uBO 的 filter

**Comment by danny0838** [comment]
regex 效能的確是一個問題，目前也在傷腦筋，目前終結內容農場也是把多個 regex 規則合併以減少總數，但是這樣就會有一些巨大的規則，比較醜。（參 #44）

或許可以考慮加個 flag，產生的規則集就分含 regex 及不含 regex 的讓使用者選XD

**Comment by danny0838** [comment]
新版用腳本及可加參數的設檔管理一些複雜規則，並加入 [hosts](https://github.com/danny0838/content-farm-terminator/tree/gh-pages/files/blocklist-hosts) 和 [ubo ](https://github.com/danny0838/content-farm-terminator/tree/gh-pages/files/blocklist-hosts)規則表，可以參考看看。
