### ISSUE TITLE
adblock規則相容性

### ISSUE THREAD

**Issue by c2xusnpq6** [danny0838/content-farm-terminator#52]
https://github.com/FutaGuard/FutaFilter/raw/master/nofarm_hosts.txt
https://github.com/festum/anti-bias-media/raw/master/ublacklist.txt

**Comment by danny0838** [comment]
@c2xusnpq6 我看不懂你想說明什麼或詢問什麼😕

**Comment by c2xusnpq6** [comment]
> https://github.com/FutaGuard/FutaFilter/raw/master/nofarm_hosts.txt
> https://github.com/festum/anti-bias-media/raw/master/ublacklist.txt

@danny0838 以上這些的格式已經是支援的了嗎?

**Comment by danny0838** [comment]
沒有支援，語法說明有寫。

**Comment by c2xusnpq6** [comment]
> 沒有支援，語法說明有寫。

所以我才在這裡請求支援 之前沒有寫清楚 非常抱歉😅😅😃🤝

**Comment by danny0838** [comment]
目前沒有計劃支援。如果要，直接安裝 uBlock origin 使用即可。
