### ISSUE TITLE
.gov.cn 不能正常訪問

### ISSUE THREAD

**Issue by c2xusnpq6** [danny0838/content-farm-terminator#54]
https://beian.miit.gov.cn/
https://www.12339.gov.cn/
http://cyberpolice.mps.gov.cn/wfjb/frame/impeach/showInformation.jsp?type=0

![image](https://user-images.githubusercontent.com/75058881/117981063-2e9d5b80-b367-11eb-8310-ad181da9a836.png)
-->
![image](https://user-images.githubusercontent.com/75058881/117981046-2b09d480-b367-11eb-8e84-767837cfea35.png)

**Comment by c2xusnpq6** [comment]
https://www.google.com/search?q=site:.gov.cn+%E4%B8%BE%E6%8A%A5

**Comment by danny0838** [comment]
目前的黑名單沒有這個網站。你安裝了哪些黑名單？是否有自己設定的黑名單？

**Comment by c2xusnpq6** [comment]
```
*.gov.cn
```

我的意思是我無法正常瀏覽網站... ^^''
![image](https://user-images.githubusercontent.com/75058881/118089681-3575ae00-b3fb-11eb-8b1c-b6c19933fcf7.png)

**Comment by danny0838** [comment]
你的意思是你封鎖該網站後，用「檢視」功能無法正常看到網站中的頁面？

**Comment by c2xusnpq6** [comment]
對~

**Comment by danny0838** [comment]
不正常的網址是哪個？

如果是照你貼圖的 https://beian.miit.gov.cn/ ，這個網頁（即使不用終結內容農場封鎖）本來就不會顯示東西，終結內容農場封鎖檢視當然不可能無中生有XD

**Comment by c2xusnpq6** [comment]
> 不正常的網址是哪個？
> 
> 如果是照你貼圖的 https://beian.miit.gov.cn/ ，這個網頁（即使不用終結內容農場封鎖）本來就不會顯示東西，終結內容農場封鎖檢視當然不可能無中生有XD

我等一下去確認 麻煩了...😅😅

**Comment by c2xusnpq6** [comment]
很奇怪 好像只會在第一次瀏覽出現... 你試試del cookie......所有有關該網站的數據

**Comment by danny0838** [comment]
問題是發生在哪個網址？

所謂出現是出現什麼？

你所謂「出現」的時候是用一般瀏覽還是用終結內容農場的檢功能？

拜託請描述清楚，不要沒頭沒尾的。我們不會讀心術。

**Comment by c2xusnpq6** [comment]
content-farm-terminator + https://beian.miit.gov.cn/
![image](https://user-images.githubusercontent.com/75058881/118401548-b1d8ed00-b698-11eb-8bf4-7c87b81aa221.png)

手動關掉content-farm-terminator 再打開 https://beian.miit.gov.cn/
![image](https://user-images.githubusercontent.com/75058881/118401539-adaccf80-b698-11eb-8d96-720ad37cec21.png)

**Comment by danny0838** [comment]
看起來此網頁是用腳本動態載入的（可關閉 JavaScript 測試），動態載入的網頁很容易受環境影響，本來就無法保證在終結內容農場的檢視模式能正常運作。

**Comment by c2xusnpq6** [comment]
那麼可以直接檢視網頁 不使用sandbox嗎? 畢竟已經提醒用戶了 也足夠了吧?

**Comment by c2xusnpq6** [comment]
多一個選擇以防萬一?

**Comment by danny0838** [comment]
那就是「解鎖」功能做的事啊...
