### ISSUE TITLE
列出中了哪個黑名單

### ISSUE THREAD

**Issue by c2xusnpq6** [danny0838/content-farm-terminator#55]
列出中了哪個黑名單 還有具體是中了黑名單的那一條規則

例如
```
黑名單: 網路黑名單 (https://github.com/sioxe823/Project-RnJlRUhL/raw/main/exaggerated_news.txt)
規則: people.com.cn
```

![image](https://user-images.githubusercontent.com/75058881/118360017-66e7a880-b5b8-11eb-8587-c810f40907f7.png)

**Comment by danny0838** [comment]
這個要再評估。理論上做得到，但是需要大幅改動程式架構，而且可能會讓效能變差。

**Comment by danny0838** [comment]
目前初步測試，的確會大幅影響效能，慢到難以接受的程度。在研究出改善效能的技術以前，大概暫時是不能實做。

（註：uBO 是使用大量複雜的技術，創造大量複雜的自訂語法，限制正規表示式的使用，才能維持比較好的效能。）

**Comment by danny0838** [comment]
前面提到的效能問題後來有研究出結果方法。因此在 5.3.0 以後即支援顯示對應的封鎖規則及名單出處。
