### ISSUE TITLE
網路黑名單更新間隔

### ISSUE THREAD

**Issue by c2xusnpq6** [danny0838/content-farm-terminator#58]
5mins? 15mins? 30mins? 1hour? 2hours?

還有..... 「清除緩存, 並立即更新」

**Comment by danny0838** [comment]
預設約每30小時自動更新。

刪除網路黑名單會刪除快取，之後再重新加入就會即使重新下載。所以「刪除→儲存選項→重新加入→儲存選項」可以達到立即更新的效果。

**Comment by c2xusnpq6** [comment]
> 所以「刪除→儲存選項→重新加入→儲存選項」可以達到立即更新的效果。

是的。 我最近一直都這樣做....... ㄔ..................................................................艮麻煩...

**Comment by danny0838** [comment]
一般來說都是自動更新即可。為什麼會需要頻繁手動更新？

**Comment by c2xusnpq6** [comment]
> 一般來說都是自動更新即可。為什麼會需要頻繁手動更新？

列表製作

**Comment by danny0838** [comment]
如果只是要測試規則，直接寫在黑名單即可，不需要寫到網路黑名單。

**Comment by c2xusnpq6** [comment]
> 如果只是要測試規則，直接寫在黑名單即可，不需要寫到網路黑名單。

這個我當然知道 但要測試的東西很多 兩個都會用到

**Comment by danny0838** [comment]
網路黑名單的規則處理方式和自訂黑名單一模一樣，即使是自製名單，我想不出有什麼「要測試的東西」必須「兩個都會用到」，你能具體說明一下嗎？

終結內容農場設計宗旨是簡便易用，一般使用者應該不太會有手動更新網路黑名單的需求，即使是自訂黑名單的開發者，此需求也不多。目前並不傾向為此把設計搞得更複雜，甚至影響程式效能。

**Comment by c2xusnpq6** [comment]
> 網路黑名單的規則處理方式和自訂黑名單一模一樣，即使是自製名單，我想不出有什麼「要測試的東西」必須「兩個都會用到」，你能具體說明一下嗎？
> 
> 終結內容農場設計宗旨是簡便易用，一般使用者應該不太會有手動更新網路黑名單的需求，即使是自訂黑名單的開發者，此需求也不多。目前並不傾向為此把設計搞得更複雜，甚至影響程式效能。
> 

沒有啦 可能我講得不夠清楚 我只是在測試我製作的列表的時候需要反覆按來按去而已 然後就在想其實部分我上面提出的功能好像不需要太多額外的硬件支出 所以就跟你講了這個idea~ 如果真的很難做到那就算吧 只能等以後了~

**Comment by danny0838** [comment]
目前為止，除了抱怨以外，我沒有看到你提出了什麼具體功能訴求。

唯一有一點像的「清除緩存, 並立即更新」已經有了，就是前面說的，刪除名單，儲存，再重新加入，儲存。

如果有具體的訴求，請寫清楚。否則要關閉了。
