### ISSUE TITLE
此附件會造成Firefox瀏覽特定網站時疑似JavaScript出錯

### ISSUE THREAD

**Issue by ImNoobody** [danny0838/content-farm-terminator#63]
網址如下
[https://www.savewizard.net/](https://www.savewizard.net/)

雖然點選停止後可正常瀏覽，但每一次進入此網站都要等10秒才會有停止選項出現
而且只有Firefox會發生，使用Chrome則不會

![圖片](https://user-images.githubusercontent.com/87736123/126408019-f83eb740-a708-47cf-9f9b-abe82988c2e1.png)

**Comment by danny0838** [comment]
試試如果把「標示網頁中的內容農場連結」選項關掉是否仍有此問題。

如果關掉就沒有，問題應該單純只是Firefox執行腳本速度較慢，因此遇到含有大量超連結的網頁就會發生腳本過慢的問題。

這個目前大概無法解決，只能等Firefox改進腳本執行速度，或哪天有高人幫我們改良演算法讓速度更快。

**Comment by danny0838** [comment]
因無進一步回應，關閉議題。
