### ISSUE TITLE
如果頁面有大量連結會導致瀏覽器崩潰

### ISSUE THREAD

**Issue by FlandreDaisuki** [danny0838/content-farm-terminator#7]
[範頁網頁](http://download.cdn.mozilla.net/pub/firefox/nightly/latest-mozilla-central-l10n/)
該頁面約 22MB 且約有 7 萬個 \<a> 標籤

感覺頁內連結可以切開處理 (1千個一組，resolve後再處理)

**Comment by danny0838** [comment]
2.2.2 把連結標示改為循序執行，數量多就慢慢標，至少不會讓瀏覽器掛掉。
