### ISSUE TITLE
關於大量免洗域名釣魚假網站之處理

### ISSUE THREAD

**Issue by mxt305** [danny0838/content-farm-terminator#72]
近期發現一堆以cacnka.xyz, procnw.xyz, keecnya.xyz, ppcnzi.xyz等系列釣魚網站為主的鏡像網頁。
大部分的分站都是使用以.co和.me域名結尾網站，內容幾乎都是關鍵字或不完整的文章堆疊。
當網站使用者從google搜尋進到這些假網頁就會導入上述4個域名結尾.xyz的網站，最後再導向viewty.xyz。
釣魚網頁多半以假問卷調查、假中獎為主。
由於這一類的網址眾多，所以之後就不在google表單上一一回報了，通常一回報就是30個起跳。
所以目前個人把這一類的網址清單整理到 https://github.com/mxt305/smashXxcnxx/blob/main/source/mirrorList.csv 供參考使用。
再者由於這些都是免洗域名，過一段時間都有失效和出現新域名的可能性，這點比較麻煩一點。
除此之外也發現以file-sharing2022.xyz, se10.biz等為主的釣魚網站，前者慣用大量的.ru域名。

**Comment by danny0838** [comment]
感謝提供資料，整理成一個清單也好，這樣處理起來會比較方便。

不曉得是否有使用什麼追蹤技術或程式？主要是重導向目標希望盡量準確，例如如果是 A.com => B.xyz => C.xyz 則 A 的重導向目標應記為 B.xyz 而非 C.xyz。這點在人工調查時很容易遺漏，因為重導向很快一下子就過去了。

域名失效方面，目前方針是繼續維持封鎖，直到確定易主成正常網站才移除。這樣做的目的主要是標示已失效農場網域連結有助於辨識導流者。

至於出現新域名目前應該無解，就是持續追查。XD

xyzList.csv 名單第三欄應該是重導向目標？很多項的值填為 top 是正常的嗎？

**Comment by danny0838** [comment]
但是像 viewty.xyz 也是最後一層，卻沒有填上 .xyz？我以為沒有重導向目標就應該直接留空白，這樣語義比較單一。

用程式撈分身我也研究過，不過怎麼下搜尋關鍵詞是一個問題，另外是 Google 搜尋如果比較頻繁很快就會被封鎖，也是要注意的地方。

**Comment by danny0838** [comment]
我還是不太理解像 `selfelementcow.top` 第三欄填 `top` 而 `viewty.xyz` 第三欄空白的理由是什麼。如果這欄不是記錄重導向，那可否另外加一欄純粹記錄重導向目標？這樣我比較方便使用。

**Comment by danny0838** [comment]
補充：

1. 說明中「傀儡」的「傀」用字錯誤

2. 可以嘗試[向 Google 檢舉](https://www.google.com/webmasters/tools/spamreportform)，這種欺騙性重導向是[明確符合 Google 對垃圾網站的定義](https://developers.google.com/search/docs/advanced/guidelines/sneaky-redirects)。（我個人是會取其中一兩個例子回報，然後在敘述文字貼上整個列表的超連結）

**Comment by mxt305** [comment]
> 補充：
> 
> 1. 說明中「傀儡」的「傀」用字錯誤
> 2. 可以嘗試[向 Google 檢舉](https://www.google.com/webmasters/tools/spamreportform)，這種欺騙性重導向是[明確符合 Google 對垃圾網站的定義](https://developers.google.com/search/docs/advanced/guidelines/sneaky-redirects)。（我個人是會取其中一兩個例子回報，然後在敘述文字貼上整個列表的超連結）

1.錯字已修正了。
2.其實有檢舉過，只是多到檢舉不完，列表還是需要隨時更新。
另外有寫一個簡單腳本只要把網址丟進去就可以幫你看下一層導向是哪一個網址，減少人工檢查的時間。只是偶爾會有一點小錯誤需要調整。

**Comment by danny0838** [comment]
我五天前檢舉了 11yourtub.co ，現在還是搜尋得到。也不曉得 Google 是否有意不處理，可能真的要檢舉量更大他們才會重視？

腳本放在哪裡？我在 repo 中好像沒看到？

**Comment by mxt305** [comment]
腳本的部分當時我還沒丟到github上所以找不到正常
剛剛已經推上去了，參見[xxcnxx-site-finder](https://github.com/mxt305/xxcnxx-site-finder)
目前用ts編寫，仍有很多待改善的地方，不過還算能用

**Comment by danny0838** [comment]
typescript 不熟XD

我自己是有用 Python 寫一些簡單的追蹤腳本（不過目前只有處理 302 redirect，沒處理這類 .xyz 站台的腳本重導向），追查到的資料會即時寫入 sqlite 資料庫。JSON 要等腳本全部跑完才寫入，無法中斷腳本也怕腳本出錯當掉，有時不太方便。不過 sqlite 不利於用 Git 版控，之後大概會再寫個匯入匯出程式方便匯出成可版控的格式。

**Comment by danny0838** [comment]
新版的終結內容農場有增加[重導向偵測](https://content-farm-terminator.blogspot.com/2022/09/farm-redirection-tracing.html)的功能，可以幫助偵測封鎖頁面的重導向。

如果能用自動化方式大量抓出類似網站當然很好，不過最困難的是最初的名單要如何取得XD

**Comment by danny0838** [comment]
感謝提供。

目前已實做聚合第三方來源的功能，過一段時間就會自動加入一些第三方列表。

此類站台增殖速度極快，另外同一個網域每次瀏覽時可能重導向到不同的網域。之後的技術開發重點應該在如何有效率地發掘出這類垃圾網域。
