### ISSUE TITLE
舉報表單的選項裏是否應該加入“劣質、批量機械翻譯”的選項？

### ISSUE THREAD

**Issue by sv158** [danny0838/content-farm-terminator#73]
最近遇到好多這樣的站點：批量機翻且轉載不注明原作；不是把簡體翻譯成繁體，就是把英文翻譯成中文...

感覺每次舉報都選”其他“好像不太好區分開來？

舉例：

1. en→zh-hant：https://www.uj5u.com/houduan/425788.html ；
    - 原文 https://stackoverflow.com/questions/71117723/how-to-automate-accept-cookies-pop-up-from-java-app-using-selenium
2. en→zh-hans： https://www.opsask.com/post/36692/selenium-java-cookie-popup-yingyongchengxu.html ；
    - 原文同上
3. zh-hans→转载→en： https://developpaper.com/ios-development-qq-mainstream-framework/ ； 
    - 來源 https://www.cnblogs.com/fadaijun/p/14325526.html ， 
    - 原文 https://blog.csdn.net/Calvin_zhou/article/details/110517815
2. zh-hans→转载→zh-hant： https://www.uj5u.com/houduan/404275.html ； 
    - 原文 https://mp.weixin.qq.com/s/PRN95i4ddZ3bZXgEBSqTsw

**Comment by danny0838** [comment]
目前選項中的「盜用他人原創」就已經包括盜譯（無論是機翻或人翻）的情形。如不註明出處可加選「轉載不附出處」。可在「其他意見」欄補充說明是盜譯自外文，如果可以最好連來源也附上。

至於是否要為另設選項區別盜譯，還要再評估。

**Comment by TonyRL** [comment]
https://github.com/arosh/ublacklist-stackoverflow-translation

**Comment by danny0838** [comment]
經考慮還是決定增加選項，以便區別可能盜譯自外文，方便調查。感謝建議。
