### ISSUE TITLE
readme.md的插件链接是否有误？

### ISSUE THREAD

**Issue by myWillison** [danny0838/content-farm-terminator#74]
点击chrome和Firefox的插件链接，跳转到的插件名叫content farm blocker，作者也不是danny，上次更新时间是2020年11月19日

**Comment by danny0838** [comment]
我看是沒有問題。能否提供螢幕擷圖？

**Comment by myWillison** [comment]
> 我看是沒有問題。能否提供螢幕擷圖？

git好像无法上传截图，可以提供跳转到的插件链接：https://chrome.google.com/webstore/detail/content-farm-blocker/opjaibbmmpldcncnbbglondckfnokfpm

**Comment by danny0838** [comment]
web介面拖放或點擊上傳按鈕就能上傳。

你點擊了哪個連結？請提供擷圖。

**Comment by myWillison** [comment]
![屏幕截图 2022-03-20 132612](https://user-images.githubusercontent.com/38159145/159149492-5a51e15c-b6e6-470a-bb6d-fe03419eb5c0.png)

**Comment by danny0838** [comment]
沒有問題啊。請仔細看，那是本套件所參考的「封鎖內容農場」套件的連結。

本套件的連結在「下載及安裝」那裡。

**Comment by myWillison** [comment]
哦哦，原来如此，不好意思）
