### ISSUE TITLE
我們網站 yipee.cc 不是內容農場，請協助移除

### ISSUE THREAD

**Issue by bochinshen** [danny0838/content-farm-terminator#78]
你好，我們網站不是內容農場，但是最近有人反應說他使用你的這個plugin時發現被列入警示，但事實很多內容農場都會直接來copy我們網站，我們也無法停止他們的行為，所以可能被誤判。，請協助移除 yipee.cc 網址移出名單，謝謝。

**Comment by danny0838** [comment]
我們不會根據網站經營者的一面之辭決定是否加入或移除，因為所有內容農場都不會承認自己是內容農場。

貴網站的內容，看起來的確符合一般[內容農場](https://zh.wikipedia.org/zh-tw/%E5%85%A7%E5%AE%B9%E8%BE%B2%E5%A0%B4)的行為，包括但不限於：大量來源不明的圖文內容、大量疑似未經授權的轉載或翻譯圖文、缺乏原創內容、匿名作者等等。

**Comment by bochinshen** [comment]
我們有供稿給yahoo news 、udn news、line today news ，經這三家認證合作，請問這也算是嗎?
【UDN聯合新聞網】
https://udn.com/author/articles/2/2241
【Yahoo 新聞/3C科技及汽車】
https://tw.news.yahoo.com/twtech.yipee.com--所有類別/archive
【Line Today 新聞】
https://today.line.me/tw/v2/publisher/101867

**Comment by danny0838** [comment]
Yahoo 等網站的確常在未嚴謹審核下轉載內容農場網站的內容，內容是否被轉貼在該等網站並不足以證明不是內容農場。

關鍵仍然在於，網站本身能否證明自己內容的原創性及獲得合法授權。

**Comment by bochinshen** [comment]
UDN聯合新聞網，就是每篇文都要他們內審完才會上，所以你的意思是說?這也不可信嗎?

**Comment by bochinshen** [comment]
理解你的立場及看法，但為表示立埸及看法不同，那我們會進行適當的對外說明報導，以免它人誤會，謝謝你的說明。
