### ISSUE TITLE
Sandbox mode not working on Firefox for Android

### ISSUE THREAD

**Issue by JasonHK** [danny0838/content-farm-terminator#79]
As the title said, the sandbox mode was broken on Firefox for Android.

I did some basic debugging, but no errors were logged by the extension. Although I discovered the sandbox viewer `<iframe />` was empty.

**Comment by danny0838** [comment]
What is the URL of the web page?

What Firefox Android version do you use?

What is the version of your browser extension?

**Comment by danny0838** [comment]
Close due to lack of further information.
