### ISSUE TITLE
第三方规则不明原因出现“*”这个全局通配符

### ISSUE THREAD

**Issue by kingofotaku** [danny0838/content-farm-terminator#81]
![_7UV5_FBTT C8PFKYG1KJ(J](https://user-images.githubusercontent.com/12953574/192776376-9139401c-bbc4-49ab-90c0-d0a82f561962.png)
![CIG5{`IR L13GB%PL F6 ED](https://user-images.githubusercontent.com/12953574/192776385-f28490ed-f667-4552-8ee7-b34fdd0cb63c.png)
我查看了这两份规则发现并没有*这一条。

**Comment by kingofotaku** [comment]
难道是新版修改了规则语法导致误识别？

**Comment by danny0838** [comment]
終結內容農場不支援 uBlacklist 格式，無法正確解析，所以不能直接訂閱，要先轉換格式

**Comment by kingofotaku** [comment]
> 終結內容農場不支援 uBlacklist 格式，無法正確解析，所以不能直接訂閱，要先轉換格式

请问应该怎么转？

**Comment by danny0838** [comment]
語法說明在套件選項頁就有附，可自行copy原始碼用文字處理器整理。

**Comment by danny0838** [comment]
@kingofotaku 補充一下，你提供的那個專案有幾個主要列表已經有做自動聚合，訂閱預設黑名單就會自動包含。

如果要進一部包含更大的列表，也可以修改後台資料庫 (gh_pages branch)的腳本做自動聚合，再 host 在自己的版本庫並用終結內容農場訂閱。
