### ISSUE TITLE
默认黑名单可能存在异常规则

### ISSUE THREAD

**Issue by whoisnian** [danny0838/content-farm-terminator#82]
访问 `.com.cn` 结尾的网站时出现内容农场提示，封锁详情为：
![Screenshot_20221012_112725](https://user-images.githubusercontent.com/23057947/195243408-a37e0381-12f2-4b69-83b3-f8fd27cce6bf.png)
在对应的黑名单 https://danny0838.github.io/content-farm-terminator/files/blocklist/content-farms.txt 中发现有该规则：
![Screenshot_20221012_113157](https://user-images.githubusercontent.com/23057947/195243574-a7dfc1c6-20a2-4b4b-aec4-a5fec1719944.png)

**Comment by whoisnian** [comment]
补充黑名单信息：
```
  # Title: Content Farm Filters
  # Description: Filter for general content farms, mostly in Chinese.
  # Last modified: 2022-10-11T17:40:14+00:00
  # Homepage: https://danny0838.github.io/content-farm-terminator/
  # Licence: MIT License
  # Source: https://danny0838.github.io/content-farm-terminator/files/blocklist/content-farms.txt
```

**Comment by WarriorFromLongAgo** [comment]
同样遇到这个问题，，com.cn就是r18。。。。

**Comment by Emily-0616** [comment]
同样遇到这个问题

**Comment by HiMetre** [comment]
服了, 把整个com.cn域名 放到规则里面

**Comment by jingouwangzi** [comment]
已暂停使用

**Comment by MZhao-ouo** [comment]
先禁用了，希望尽快修复

**Comment by danny0838** [comment]
抱歉造成困擾，這是因為我們在清理一些垃圾網站的子域名時沒檢查到。已於 1d9b7989cbdc85cf04eefdcb406d23937a0d2161 修正發布新版名單。

預設情況下要24小時後才會更新快取，如果要立即強制更新，可先退訂再重新訂閱名單。具體來說可以把「網路黑名單」欄的 `https://danny0838.github.io/content-farm-terminator/files/blocklist-hosts/content-farms.txt` 前面加上一個空白（因為**空白及以後的字元會視為註解**，實際上會讓它變成空規則而取消訂閱），儲存，此時這個網路黑名單會被刪除，快取也會被清除，之後再進入選項把空白移除，儲存，就會重新下載最新版原始碼及建立快取。

以後若遇到類似情況可先把想取消的規則加入**灰名單**（5.7.0 版新增功能），灰名單的作用即是使特定規則失效，在這種情況比白名單更適合，因為白名單會強制阻止封鎖符合的網站，如果加入 `com.cn` 可能會導致一些想封鎖的網域如 `bad1.com.cn`、`bad2.com.cn`、……無法被封鎖，而如果要個別在白名單中加入想解封的網站 `normal1.com.cn`、`normal2.com.cn`、……則會非常麻煩。

最近有些熱情人士大量舉報某些有多重複本的垃圾網站，一天好幾百條，我們一時要審查、更新名單會比較吃力。建議之後若要舉報大量類似性質的網域，可以發新 issue 甚至 pull request，如果有意願持續更新維護類似垃圾站台名單，也可以自行整理一個黑名單發布在 GitHub，我們可以視情況用自動聚合的方式處理，以加快處理速度。
