### ISSUE TITLE
Question - can content farms be sent to web safety services

### ISSUE THREAD

**Issue by nicoleahmed** [danny0838/content-farm-terminator#84]
Hi 
Great work tackling the annoying issue of content farms

I wasn't sure what is meant by terminator.

When sites are marked as content farms using the extension is there a report sent to any web safety sites? Like netcraft, abuseipdb, www.scamadviser.com, safeweb.norton.com etc

I think doing this would be amazing

**Comment by danny0838** [comment]
No, currently there is no feature about automatic reporting.

There is also no plan to implement it as there are too many issues to consider and is out of the scope of this project. You can report them to such projects manually on your own.
