### ISSUE TITLE
thesaurus.com is blocked accidentally

### ISSUE THREAD

**Issue by xatier** [danny0838/content-farm-terminator#86]
This site was added in https://github.com/danny0838/content-farm-terminator/commit/1d68e2780af643f6754be1033eeae753d7c3a5a2

**Comment by danny0838** [comment]
Further explanation/rationale?

**Comment by xatier** [comment]
This is a legitimate dictionary site, not a CF.

**Comment by danny0838** [comment]
Thanks. We have checked that.

Please provide at least minimal reasoning when reporting a false content farm. We may reject bad reports that provides no reasoning as some content farm founders are abusing by keeping asserting that their sites are "incorrectly included".
