### ISSUE TITLE
uBlock Origin版本黑名單未跟從正確的語法

### ISSUE THREAD

**Issue by TotalImportance8529** [danny0838/content-farm-terminator#88]
黑名單：
https://danny0838.github.io/content-farm-terminator/files/blocklist-ubo/content-farms.txt

可以看到有一系列規則都並未使用uBlock Origin的正規語法編寫，並且造成黑名單在Brave瀏覽器的內置廣告攔截器運作不正常。
https://community.brave.com/t/filterlist-do-not-work-on-brave/512122/2

uBlock Origin的語法可以參考github的維基頁面
英文版：https://github.com/uBlockOrigin/uBlock-issues/wiki/Static-filter-syntax
簡體中文翻譯：https://github.com/fang5566/uBlock/wiki/%E9%9D%99%E6%80%81%E8%BF%87%E6%BB%A4%E8%A7%84%E5%88%99%E8%AF%AD%E6%B3%95

https://github.com/DandelionSprout/adfilt/blob/master/Wiki/SyntaxMeaningsThatAreActuallyHumanReadable.md#file-blocking-aka-blocking-rules-aka-non--rules

**Comment by danny0838** [comment]
請具體說明是哪條規則及如何不正常

**Comment by TotalImportance8529** [comment]
以及註解`03tity.me  #redirects to fatbean.xyz` 應該轉換為
```
! redirects to fatbean.xyz
||03tity.me^ 
```

**Comment by TotalImportance8529** [comment]
請參考以上我提供的鏈結，以及@DanSnow提供的正確版本清單。

**Comment by danny0838** [comment]
1. 你提供的文件就有寫到 `example.com` 等價於 `||example.com^`
2. 實測輸入 `example.com  #comment` 在 uBO (1.52.2) 自動上色顯示 `#comment` 為註解，實測進入 `example.com` 頁面也可以正常處理，並且封鎖頁面顯示其封鎖規則為 `||example.com^`，證明二者等價

因此就我看來這樣的寫法完全符合 uBO 的語法，並無錯誤。如前所述，如果你認為錯誤，請舉實例說明哪條語法在哪個情況下發生異常。

**Comment by TotalImportance8529** [comment]
> 2\. 自動上色

自動上色是表示規則出錯，不是指註解。因為##在uBO中是用來指定要處理的元素的。
https://adguard.com/kb/general/ad-filtering/create-own-filters/#cosmetic-rule

> 1. `example.com` 等價於 `||example.com^`

https://adguard.com/kb/general/ad-filtering/create-own-filters/#examples

在uBO沒有問題不一定代表在其他廣告攔截器沒有問題，例如我提到的Brave，其中Brave不支援HOSTS文件。
值得注意的是僅使用example.com依然等同於使用HOSTS文件，例如輸入 `1.1.1.1 example.com` 在uBO中依然會阻止example.com，因此可以推測的是uBO實際上忽略了IP地址，並僅處於域名。

**Comment by danny0838** [comment]
1. 規則沒有出錯，如果真的出錯，就不可能能正常封鎖並且還顯示規則為 `||example.com^`。你拿 AdGuard 的文件也不能證明 uBO 的規則如何。再次重申，你要主張有錯就請舉出使用 uBO 出錯的實際案例。
2. 我們提供的 uBO 規則只保證支援 uBO。我們作為第三方名單提供者，目前沒更多心力去研究其他類似工具的語法及處理各種可能的規則不一致，還請諒解。

**Comment by TotalImportance8529** [comment]
夠了，你們不願意提供改正版本，那就算了。
