### ISSUE TITLE
轉址到正確網站的功能

### ISSUE THREAD

**Issue by SmallBeeWayne** [danny0838/content-farm-terminator#89]
有些網站，尤其是幾個PTT鏡像站，能夠透過簡單的正規表示式轉換到正確網址，例如：

`https:\/\/www\.pttweb\.cc\/bbs\/([^\/]+)\/(.+) 轉換到 https://www.ptt.cc/bbs/$1/$2.html`
`https:\/\/moptt\.tw\/p\/([^.]+).(.+) 轉換到 https://www.ptt.cc/bbs/$1/$2.html`

是否能新增一個功能，透過一個按鈕或選項轉換這類網站?

**Comment by danny0838** [comment]
這並非本套件主要功能，也無法簡單和現有黑白名單語法相容，因此不考慮。請找其他合適套件。
