### ISSUE TITLE
用 async/await 重構

### ISSUE THREAD

**Issue by FlandreDaisuki** [danny0838/content-farm-terminator#9]
看了一下作者有意重構並簡化程式碼(2.2.4)
有考慮用 async / await 來取代 Promise 嘛？
~~雖然如果要 catch 要用 try-catch 有點醜~~

我不確定 Chrome / 手機版會不會炸掉，但 Fx 57+ 桌面版應該是不太會炸掉才對

**Comment by danny0838** [comment]
async/await 需求 Chrome >= 55、Firefox >= 52 比目前支援的 Chrome >= 49、Firefox >= 48 少太多，且涉及整個語法架構無法 polyfill，目前不考慮。
