### ISSUE TITLE
火山引擎被列入了黑名单是怎么回事

### ISSUE THREAD

**Issue by borisxxz** [danny0838/content-farm-terminator#90]
volcengine.com把整个api都拉入了黑名单，我点个翻译API都要解锁五六次

**Comment by danny0838** [comment]
因為此站確實有生產垃圾內容之內容農場行為，因此被回報及加入封鎖。

一個網站可能有一定程度的多面性，有些內容農場可能會提供特定服務，或說提供服務的網站有的會做內容農場的勾當，造成判定的困難。我們還需要一些時間調查及研議該如何處理此站。如果你個人認為該站的服務對你很重要，可先加入灰名單。

**Comment by danny0838** [comment]
目前已取消全站封鎖，只封鎖 volcengine.com/themes，如有進一步想法請提出。
