### ISSUE TITLE
关于"tool.lu"工具类网站误封锁

### ISSUE THREAD

**Issue by ghost** [danny0838/content-farm-terminator#91]
**经过检查，我认为tool.lu网站并没有任何垃圾和抄袭内容**

**Comment by danny0838** [comment]
熱梗詞典下面有大量疑似抄襲的內容，沒有附上來源。且許多頁面都有一模一樣的假評論。

例如：
https://tool.lu/meme/detail.html?id=fV
https://tool.lu/meme/detail.html?id=fR
https://tool.lu/meme/detail.html?id=fQ
