### ISSUE TITLE
希望能够给扩展的设置页面添加深色模式

### ISSUE THREAD

**Issue by DeepChirp** [danny0838/content-farm-terminator#93]
希望能够给扩展的设置页面添加深色模式，目前白色在深色模式下看着有些刺眼，谢谢。

**Comment by danny0838** [comment]
我們大概不會考慮太複雜的樣式設定。你可以考慮用 user style 處理。

**Comment by DeepChirp** [comment]
@danny0838 您可能误解了我的意思。我的意思是为设置页面（见下图）添加深色模式，并没有改变其他的样式，这应该不是太复杂的样式设置。user style似乎不能改变受保护的页面的样式吧。
![图片](https://github.com/danny0838/content-farm-terminator/assets/66902050/52dbe4a0-c7ea-4160-9ac1-418a583de450)

**Comment by danny0838** [comment]
Firefox 的 userChrome.css 應該是做得到，不過我沒實際研究過。

要做暗色系主題就是要二套樣式，視情況的可能有相當的複雜度。有空再研究了......

**Comment by DeepChirp** [comment]
> Firefox 的 userChrome.css 應該是做得到，不過我沒實際研究過。
> 
> 要做暗色系主題就是要二套樣式，視情況的可能有相當的複雜度。有空再研究了......

简单用@media (prefers-color-scheme: dark)来实现了一下，感觉效果还可以，至少没之前那么刺眼了

**Comment by danny0838** [comment]
implemented.
