### ISSUE TITLE
content-farms.txt contains an official government website where you can look up the law

### ISSUE THREAD

**Issue by galantra** [danny0838/content-farm-terminator#96]
The website I mean is [landesrecht.rlp.de](http://landesrecht.rlp.de/). It is a web portal for the law of Rhineland-Palatinate, one of the 16 federal states of Germany. Its inclusion in the default blacklist seems like a clear mistake to me.

**Comment by danny0838** [comment]
Removed. Thank you for the feedback.

**Comment by Retia-Adolf** [comment]
In `https://danny0838.github.io/content-farm-terminator/files/blocklist/extra-content-farms.txt`, it is still included? I'm not sure what is the criteria for the extra list, like even nasa.gov is included? and several others: 

```
rlp.de #!scyrte
nasa.gov #!scyrte
medium.com #!scyrte  # sometimes it requires login to read full article but not all
ctan.org #!scyrte           # TeX archive, definitely not a content farm? if we don't equate a package index site to content farm
```

**Comment by danny0838** [comment]
Removed scyrte from aggregation sources as it's inclusion criteria is not transparent enough and is too likely to include normal web sites.
