### ISSUE TITLE
黑名单里有被误伤的网址

### ISSUE THREAD

**Issue by Shinolr** [danny0838/content-farm-terminator#97]
这个source里：
```
  # Title: Content Farm Filters
  # Description: Filter for general content farms, mostly in Chinese.
  # Last modified: 2024-08-04T19:50:06+00:00
  # Homepage: https://danny0838.github.io/content-farm-terminator/
  # Licence: MIT License
  # Source: https://danny0838.github.io/content-farm-terminator/files/blocklist/content-farms.txt
```
[bg3.co](https://bg3.co)，这个link被屏蔽没问题，但是它的path下是一个小说网站具体章节，比如：[https://tw.bg3.co/novel/pagea/[具体章节信息].html](https://tw.bg3.co/novel/pagea/chulong-liudanpashui_524.html)

复现步骤：
小说网站的地址是[https://tw.ttkan.co/](https://tw.ttkan.co/)，在这里选择随便一本书，点进章节后，就会跳转到`bg3.co/novel/pagea/[具体章节信息]`

**Comment by danny0838** [comment]
你認為哪個網站是被誤傷？

初步看來，就是因為有內容農場行為且互相連結導流，因此二者皆判定為內容農場。

**Comment by Shinolr** [comment]
虽然[bg3.co](bg3.co)是内容农场应该被ban，但是`/novel/pagea/*`下的内容没问题啊。
是否支持ban掉域名，而放行具体的path？
✖️：`bg3.co`
✔️：`bg3.co/novel/pagea/*`

**Comment by danny0838** [comment]
通常如果一個網站主體是內容農場，就是封鎖整個網域。除非只有特定 path 下是農場才會只對 path 封鎖。

**Comment by Shinolr** [comment]
> 通常如果一個網站主體是內容農場，就是封鎖整個網域。除非只有特定 path 下是農場才會只對 path 封鎖。
> 
> 技術上來說，目前未提供網路白名單，因為容易被濫用。當然要用 regex 把封鎖規則改i戶對全網域除部分路徑外並非不可行，但很麻煩且難維護。
> 
> 這種狀況一般使用者自己針對特定路徑加白名單即可。

用户可以针对特定的 path加白名单吗？
我在 Syntax help 里看到有 Auto-correction 的功能。
> 5. Auto-correction
> 
> Entered rules will be auto-corrected. A standard rule will be converted to the corresponding domain name. For example, these rules:
> 
>     www.example.com
>     http://example.com
>     example.com:8000
>     http://example.com/somepage.html
> 
> will be corrected to:
> 
>     example.com

`https://cn.bg3.co/novel/pagea/*.html` 被纠正成了 `cn.bg3.co`。

**Comment by danny0838** [comment]
語法說明都有寫，如果不是純域名，而是含有路徑，就要用regex，比如 `^https://cn\.bg3\.co/novel/pagea/.*?\.html(?=[/?#]|$)`

**Comment by Shinolr** [comment]
感谢，知道了，囫囵吞枣了，没有细读。
